x <- rnorm(100, mean = 5, sd=2)
var(x)
mean(x)
y <- ((x*5)+2)+runif(100,0,0.1)
pdf('graph1.pdf', height = 4, width = 4)
plot(x,y)
abline(lm(y~x), col='orange')
dev.off()
coef(lm(y~x))
### (intercept)y= 2.053240 x=4.998827, its not perfect 2 and 5 because the mean and variance was not exactly 2 and 5 respectively, furthermore there was also addition of small numbers. 
z <- c()
x <- rnorm(100, mean=5, sd=2)
for(i in 1:100) {
	z[i] <- runif(1)
	y <- (x * z[i]) + 2 + (rnorm(100, 0:0.1))
	I <- coef(lm(z[1:100]~y))
	}
	pdf('graph2.pdf', height = 4, width = 4)
	plot(z[1:100], y)
	abline(lm(y~z[1:100]))
	dev.off()
	pdf('graph3.pdf', height = 4, width = 4)
	plot(c(z, -0.029))
	dev.off()
	install.packages("meme")
	library('meme')
	dir()